### ISSUE TITLE
selectedLava doesn't apply when menu is collapsed?

### ISSUE THREAD

**Issue by fversepuy** [jtnix/jQuery-LavaLamp#8]
Hi, 

I'm using LavaLamp with twitter bootstrap. On big screens (when the menu is visible) it works like a charm. But on mobile devices (when the menu is collapsed), when I click on the hamburger icon, the selected item is not styled.

I didn't find what's the problem, for now. If someone's got an idea...

**Comment by jtnix** [comment]
This plugin is not designed for mobile devices which rely on touch events and cannot respond to `:hover` selectors appropriately.
