### ISSUE TITLE
(...).lavaLamp is not a function error

### ISSUE THREAD

**Issue by psutinrerk** [jtnix/jQuery-LavaLamp#9]
Hello I got the following error not sure what happen
$(...).lavaLamp is not a function

I'm using JQuery 1.11
this is what I used to call LavaLamp
$(".uk-navbar-nav").lavaLamp({speed: 700});

also is there a way to change the color of backLava to different color when hover on different 'li'?

Thank you

**Comment by jtnix** [comment]
Hi, I am not sure what your problem was, but it seems like the LavaLamp plugin was not being loaded for you to get the first error.

To answer your other question, using the .hoverFinish callback, you could dynamically change the .backLava styling when hovering the appropriate element.
